### ISSUE TITLE
Classes with the <<relator>> stereotype cannot specializes others with the same stereotype

### ISSUE THREAD

**Issue by prouzpe3** [OntoUML/OntoUML#14]
RELATOR has relator as subtype/supertype, which is not allowed
EX1 and (EX2 - both diagrams) on page about MIXIN
EX3 on page about ROLE
EX2 on page about ROLEMIXIN

**Comment by claudenirmf** [comment]
This must be updated now that <<relator>> represents a ultimate sortal in OntoUML 2.

**Comment by claudenirmf** [comment]
This ends up being the same issues as #6 now. Let's focus the discussion there.
