### ISSUE TITLE
Role / Phase inheritance contradiction

### ISSUE THREAD

**Issue by MichaelVrana** [OntoUML/OntoUML#20]
Phase has Role as an allowed supertype, but Role doesn't have a Phase as an allowed subtype.

**Comment by MarekSuchanek** [comment]
This has been done in https://github.com/OntoUML/OntoUML/commit/de895c3485a47f0a71c0080d368de2284f3004e6 ...

I don't understand how it could be possible to make a relationally independent subtype (Phase) of Role which is relationally dependent. I could not find clear explanation in thesis not OntoUML 2.0 specification.

Any clarification @tgoprince, please? Can be Phase-type used as subtype of Role-type?

**Comment by tgoprince** [comment]
It definitely makes sense for a phase to be specialized into a role (e.g. only an adult can be a full-time employee, only a deceased person can be nominated for a posthumous award). Thus, this configuration is allowed in OntoUML.

I'm not so sure, however, that the inverse makes sense.
In any case, currently there is no rule in OntoUML that forbids a phase to specialize a role. I'm considering both [Giancarlo's book](https://ris.utwente.nl/ws/portalfiles/portal/6042428/thesis_Guizzardi.pdf) and our [2018 paper on endurant types](https://www.researchgate.net/publication/325995419_Endurant_Types_in_Ontology-Driven_Conceptual_Modeling_Towards_OntoUML_20).

**Comment by NejakejTomas** [comment]
The same is true for the Phase and PhaseMixin, PhaseMixin has Phase as one of the allowed subtypes, but Phase is missing PhaseMixin as allowed supertypes.
Same also applies for Mode, according to the docs it can have itself as a subtype but not as a supertype:
![image](https://user-images.githubusercontent.com/40525630/98816762-6ca5db00-2429-11eb-9162-19d75c6ccdf7.png)

**Comment by claudenirmf** [comment]
We haven't settled on this matter yet, so I cannot rule out the possibility. For instance, could be interest to represent the phases of an employment contract as "junior phase" and "senior phase". In this case, what changes is an intrinsic property of the `Employment` relator (its age), but I don't have strong feelings about the stereotype on the subclasses of `Employee`. If it is better to model `Junior Employee` and `Senior Employee` as phases I cannot say.

Therefore, let's add phases as possible subtypes of roles for the moment.

**Comment by MarekSuchanek** [comment]
But this one says that Phase cannot be a subtype of role, right? 😄 

https://dev.ontouml.org/docs/constrains/ontouml-v2/specialization-table/

**Comment by claudenirmf** [comment]
@MarekSuchanek, thanks for catching that. If we agree to this idea of not adding constraints in situations the theory is not yet settled, I would change that as well.

By the way, we may prefer to have the documentation of the actual language in a single place. We could focus dev.ontouml.org on tooling instead.

**Comment by MarekSuchanek** [comment]
I agree, if it is not (yet) forbidden, we should also not forbid it in the documentation. I am honestly not sure what is the latest "official" opinion on this 😄 

With my reasoning and for your example, I would say that `Junior Employee` and `Senior Employee` are still relationally dependent on the `Employment` just as the more generic `Employee`, thus cannot be phases... Would be definitely an interesting discussion, maybe even with proofs.

**Comment by pedropaulofb** [comment]
> The same is true for the Phase and PhaseMixin, PhaseMixin has Phase as one of the allowed subtypes, but Phase is missing PhaseMixin as allowed supertypes. 

Thank you for your message. This issue was already solved.

> Same also applies for Mode, according to the docs it can have itself as a subtype but not as a supertype: 

The generalization and specialization for modes are correct in the current version of the specification. It cannot have another mode as a supertype nor as a subtype.

**Comment by pedropaulofb** [comment]
> By the way, we may prefer to have the documentation of the actual language in one single place. We could focus dev.ontouml.org on tooling instead.

I totally agree with that.

**Comment by pedropaulofb** [comment]
> @MarekSuchanek, thanks for catching that. If we agree to this idea of not adding constraints in situations the theory is not yet settled, I would change that as well.

> I agree, if it is not (yet) forbidden, we should also not forbid it in the documentation. I am honestly not sure what is the latest "official" opinion on this 😄

> I agree with @MarekSuchanek

As agreed by @claudenirmf, @MarekSuchanek, and @tgoprince, we are not going to make the specification overconstrained. Hence, I am proposing a PR for allowing Phases as subtypes of Roles. By the way, I also agree with this position.
