### ISSUE TITLE
Mode and Quality are missing the meta section

### ISSUE THREAD

**Issue by TonyVlcek** [OntoUML/OntoUML#21]
[Mode](https://ontouml.readthedocs.io/en/latest/classes/aspects/mode/index.html) and [Quality](https://ontouml.readthedocs.io/en/latest/classes/aspects/quality/index.html) are missing the meta section, I think that it has something to do with this:
```
...
provides_identity: ?
...
```
Do these two provide identity? If it can't be said whether they do or don't is there a way that the .yml can be edited so that it doesn't break the rendering of the `stereotype` block?

E.g.:
![image](https://user-images.githubusercontent.com/4984658/68431017-86c33280-01b1-11ea-928e-c31c09ee6350.png)

**Comment by claudenirmf** [comment]
It looks like this issue has already been solved, so I am closing this issue.
