### ISSUE TITLE
Uncertainty about Relator constraints

### ISSUE THREAD

**Issue by tonyskansf** [OntoUML/OntoUML#24]
The second constraint (C2) for [Relator](https://ontouml.readthedocs.io/en/latest/classes/sortals/relator/index.html?highlight=relator#constraints) might be out-dated. I believe it is not always possible to model the domain so that this requirement is met.

**Comment by claudenirmf** [comment]
A relator is a relational moment, thus, it cannot exist if it not "relating" (connecting) at least two endurants.

But maybe you had something in mind that I am not considering. Could you share some example?

I will close the issue for now, but we can open it again later if necessary without a problem.
