### ISSUE TITLE
RIGIDITY terminology

### ISSUE THREAD

**Issue by graham-meaden** [OntoUML/OntoUML#25]
Hi, just a suggestion...

Having read the page on RIGIDITY, I think English may not be your native language but reading your commentary I think
RIGID = Intrinsic
ANTI-RIGID = Transient

This change in terminology would make reading and writing about the subject much easier, IMHO.

**Comment by claudenirmf** [comment]
Rigid types are those that necessarily apply to all their instances, while anti-rigid ones apply "possibly" (in a modal sense). For example, instances of the type `Person` are instances of it as long as they exist, while a person is instance of `Student` only as long as they hold an enrollment at some educational institution.

UFO uses the notion of "intrinsic" on aspects of endurants (i.e., properties). Intrinsic properties are those that existentially depend o a unique endurant who is its bearer. In other words, a person's height is an intrinsic property of that person. Intrinsic properties (referred to in this sense as moments) are defined in opposition to relational properties, which are existentially dependent on all the endurants they relate.
