### ISSUE TITLE
Add Relator, Mode, and Quality and allowed supertypes of classes decorated and Subkind, Role, or Phase

### ISSUE THREAD

**Issue by jmartinkova** [OntoUML/OntoUML#26]
Na stránce stereotypu Mode a Quality je uveden stereotyp Subkind jako možný podtyp. 
![2021-05-05_19h08_02](https://user-images.githubusercontent.com/83722371/117181525-9d157300-add5-11eb-9f81-f71150d31e31.png)
![2021-05-05_19h08_31](https://user-images.githubusercontent.com/83722371/117181540-a272bd80-add5-11eb-8615-62821e2c0c9f.png)
Naopak na stránce stereotypu Subkind nejsou Mode a Quality uvedeny jako jeho možné nadtypy. 
![2021-05-05_19h08_54](https://user-images.githubusercontent.com/83722371/117181691-cf26d500-add5-11eb-9fbc-9d5cf5e9936e.png)

**Comment by claudenirmf** [comment]
Automatic translation of this issue. Please apologize any mistakes.

Original text:

> Subkind nemá definován Mode a Quality jako možný nadtyp, ale měl by mít
>
> Na stránce stereotypu Mode a Quality je uveden stereotyp Subkind jako možný podtyp.
> ![](https://user-images.githubusercontent.com/83722371/117181540-a272bd80-add5-11eb-8615-62821e2c0c9f.png)
> 
> Naopak na stránce stereotypu Subkind nejsou Mode a Quality uvedeny jako jeho možné nadtypy.
> ![](https://user-images.githubusercontent.com/83722371/117181691-cf26d500-add5-11eb-9fbc-9d5cf5e9936e.png)

**Comment by pedropaulofb** [comment]
Thank you @jmartinkova for reporting this problem. The problem was already solved, so I am closing this issue.
