### ISSUE TITLE
Add Category among the list allowed supertypes of RoleMixin

### ISSUE THREAD

**Issue by jmartinkova** [OntoUML/OntoUML#27]
V definici RoleMixinu není uvedena Category jako možný nadtyp. Model v části příklady tento vztah ale umožňuje.
![image](https://user-images.githubusercontent.com/83722371/117182149-49575980-add6-11eb-8299-25d314973a69.png)
![image](https://user-images.githubusercontent.com/83722371/117182155-4bb9b380-add6-11eb-854d-252ef642c26d.png)

**Comment by claudenirmf** [comment]
Automatic translation of this issue. Please apologize any mistakes.

> RoleMixin nemá definovanou Category jako možný nadtyp, dle obrázku z příkladů by to mělo být možné
>
> V definici RoleMixinu není uvedena Category jako možný nadtyp. Model v části příklady tento vztah ale umožňuje.
> ![](https://user-images.githubusercontent.com/83722371/117182149-49575980-add6-11eb-8299-25d314973a69.png)
> ![](https://user-images.githubusercontent.com/83722371/117182155-4bb9b380-add6-11eb-854d-252ef642c26d.png)

**Comment by claudenirmf** [comment]
Closing this issue in favor of #29 which is more general.
