### ISSUE TITLE
Mixin and Mode, Quality (not consistent)

### ISSUE THREAD

**Issue by cermaj25** [OntoUML/OntoUML#46]
V dokumentaci není konzistentní informace - Mode a Quality nejsou uvedeny u Mixinu jako možné podtypy, naopak u Mode i Quality je, že Mixin může být jejich nadtyp.
![image](https://user-images.githubusercontent.com/89933969/140769455-f511f45f-17f6-4bef-9a59-5cf087a476ba.png)
![image](https://user-images.githubusercontent.com/89933969/140769514-737f10ae-ea38-4f69-9271-02655eea1aa9.png)
![image](https://user-images.githubusercontent.com/89933969/140769543-41031cd8-04bc-4d95-93f9-a368ca97e20f.png)

**Comment by kuchejak** [comment]
Stejný problém je pro Mode a Quality i u Category

**Comment by belohma2** [comment]
Fixed in 19.11. nightly build.
