### ISSUE TITLE
Role and Phase (not consistent)

### ISSUE THREAD

**Issue by cermaj25** [OntoUML/OntoUML#47]
Phase má uvedeno, že Role může být jejím nadtypem, ale Role má uvedeno, že jejím podtypem může být pouze Role.
![image](https://user-images.githubusercontent.com/89933969/140770083-27bd75d9-ab09-4dc2-9f4d-938def16d82c.png)
![image](https://user-images.githubusercontent.com/89933969/140770121-4946b041-7d77-4151-89d2-796eed01e3dc.png)

**Comment by belohma2** [comment]
Tento problém má již existující issue, každopádně máte bod za nalezení této nekonzistence.
