### ISSUE TITLE
Mixin and PhaseMixin (not consistent)

### ISSUE THREAD

**Issue by kuchejak** [OntoUML/OntoUML#48]
Similar to issues #46 and #47 by cermaj25, Mixin and PhaseMixin are not described consistently. PhaseMixin is not mentioned on Mixin page in section Allowed subtypes, but Mixin is mentioned on PhaseMixin page in section Allowed supertypes. 

![image](https://user-images.githubusercontent.com/94016085/141000583-41502a99-15bd-4a8a-a497-cffca53cbf63.png)
![image](https://user-images.githubusercontent.com/94016085/141000603-ce36f8d2-3d07-4494-a0d6-6a49cf9319b8.png)

**Comment by belohma2** [comment]
Fixed in 19. 11. nightly build.
