### ISSUE TITLE
Mode (not consistent)

### ISSUE THREAD

**Issue by popovma1** [OntoUML/OntoUML#49]
Similar to issues #46 and #47 by cermaj25 and #48 by kuchejak, Mode is subtype of Mode, therefore should be also a supertype
![obrázok](https://user-images.githubusercontent.com/91681881/141001602-2deb59b3-d908-44c2-8ac4-06567d527f41.png)

**Comment by belohma2** [comment]
Fixed in nightly build 19. 11. 2021.
