### ISSUE TITLE
PhaseMixin cannot be a supertype of Phase

### ISSUE THREAD

**Issue by jmeinlschmidt** [OntoUML/OntoUML#53]
As specified in **Phase** `Allowed supertypes` (https://ontouml.readthedocs.io/en/latest/classes/sortals/phase/index.html) **PhaseMixin** is missing. However, **Phase** is mentioned as an `Allowed subtype` of **PhaseMixin** (https://ontouml.readthedocs.io/en/latest/classes/nonsortals/phasemixin/index.html).

**Comment by belohma2** [comment]
Fixed in nightly build 19. 11. 2021.
