### ISSUE TITLE
Quality cannot be a subtype of Category

### ISSUE THREAD

**Issue by jmeinlschmidt** [OntoUML/OntoUML#54]
As specified in **Category** `Allowed subtypes` (https://ontouml.readthedocs.io/en/latest/classes/nonsortals/category/index.html) **Quality** is missing. However, Category is mentioned as an `Allowed supertype` of Quality (https://ontouml.readthedocs.io/en/latest/classes/aspects/quality/index.html).

![image](https://user-images.githubusercontent.com/13226284/141195871-86841cb7-ed18-4331-bd47-cfaf990882dd.png)
![image](https://user-images.githubusercontent.com/13226284/141195905-867add92-2e1a-4361-92ce-a928982509a5.png)

**Comment by belohma2** [comment]
Fixed in nightly build 19. 11. 2021.
