### ISSUE TITLE
Quality cannot be a supertype of Phase/Role

### ISSUE THREAD

**Issue by jmeinlschmidt** [OntoUML/OntoUML#55]
https://ontouml.readthedocs.io/en/latest/classes/aspects/quality/index.html
![image](https://user-images.githubusercontent.com/13226284/141202930-da2c6fb7-471d-42e9-b820-4f45cb6ba9f2.png)
![image](https://user-images.githubusercontent.com/13226284/141203014-cebc4b4d-6dad-4c74-931e-7e4ccf3934eb.png)
https://ontouml.readthedocs.io/en/latest/classes/sortals/role/index.html
![image](https://user-images.githubusercontent.com/13226284/141203824-a5e3895b-90da-4198-b98e-b7ecd3fb7406.png)

**Comment by belohma2** [comment]
Fixed in nightly build 19. 11. 2021.
