### ISSUE TITLE
Mode cannot be a supertype of Phase/Role

### ISSUE THREAD

**Issue by jmeinlschmidt** [OntoUML/OntoUML#56]
https://ontouml.readthedocs.io/en/latest/classes/aspects/mode/index.html
![image](https://user-images.githubusercontent.com/13226284/141203629-df1b6183-f897-4df0-ac97-1f588af0e134.png)
https://ontouml.readthedocs.io/en/latest/classes/sortals/phase/index.html
![image](https://user-images.githubusercontent.com/13226284/141203646-b77917cc-1076-400e-be57-bc973c4f7c30.png)
https://ontouml.readthedocs.io/en/latest/classes/sortals/role/index.html
![image](https://user-images.githubusercontent.com/13226284/141203748-eee25a79-3f9e-4553-9700-2110223f2ba6.png)

**Comment by belohma2** [comment]
Fixed in nightly build 19. 11. 2021.
