### ISSUE TITLE
Quality cannot be a subtype of Category

### ISSUE THREAD

**Issue by jmeinlschmidt** [OntoUML/OntoUML#57]
https://ontouml.readthedocs.io/en/latest/classes/nonsortals/category/index.html
![image](https://user-images.githubusercontent.com/13226284/141205485-10806985-6204-4dde-aa98-dbc20654d193.png)
https://ontouml.readthedocs.io/en/latest/classes/aspects/quality/index.html
![image](https://user-images.githubusercontent.com/13226284/141205519-44e186db-ffbd-4bfb-aa72-ad2111c49b1e.png)

**Comment by belohma2** [comment]
Fixed in nightly build 19. 11. 2021.
